[package]
name = "log-enrich"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]

[dependencies]
futures = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
log = "*"
env_logger = "*"
take_mut = "*"